version: "3"
services:
  teampass:
    image: teampass/teampass
    restart: always
    environment:
      VIRTUAL_HOST: "${TEAMPASS_HOSTNAME}"
      LETSENCRYPT_HOST: "${TEAMPASS_HOSTNAME}"
      LETSENCRYPT_EMAIL: "${LETSENCRYPT_EMAIL}"
    volumes:
      - ./files:/var/www/html
    expose:
      - 80

  mysql:
    image: mysql/mysql-server:5.7
    restart: always
    environment:
      MYSQL_DATABASE: "${DB_NAME}"
      MYSQL_USER: "${DB_USER}"
      MYSQL_PASSWORD: "${DB_PASS}"
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASS}"
    volumes:
      - ./mysql_data:/var/lib/mysql

networks:
  default:
    external:
      name: ${NETWORK}
