services:
  weblate:
    image: weblate/weblate:5.11
    restart: always
    volumes:
      - weblate_data:/app/data
      - weblate_cache:/app/cache
    depends_on:
      - database
      - cache
    env_file:
      - .env
    environment:
      WEBLATE_SITE_DOMAIN: "${WEBLATE_HOSTNAME}"
      VIRTUAL_HOST: "${WEBLATE_HOSTNAME}"
      VIRTUAL_PORT: 8080
      LETSENCRYPT_HOST: "${WEBLATE_HOSTNAME}"
      LETSENCRYPT_EMAIL: "${LETSENCRYPT_EMAIL}"

  database:
    image: postgres:17
    restart: always
    volumes:
      - postgres_17_data:/var/lib/postgresql/data
    env_file:
      - .env

  cache:
    image: redis:7
    restart: always
    volumes:
      - redis_data:/data
    env_file:
      - .env
    command: ["redis-server", "--appendonly", "yes"]

networks:
  default:
    name: ${NETWORK}
    external: true

volumes:
  weblate_data: {}
  weblate_cache: {}
  postgres_17_data: {}
  redis_data: {}
