version: "3"
services:
  gitlab:
    hostname: gitlab
    container_name: gitlab
    restart: always
    image: gitlab/gitlab-ce:latest
    extra_hosts:
      - "${GITLAB_HOSTNAME}:127.0.1.1"
      - "${REGISTRY_HOSTNAME}:127.0.1.1"
    container_name: gitlab
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'https://${GITLAB_HOSTNAME}'
        nginx['listen_port'] = 80
        nginx['listen_https'] = false
        nginx['proxy_set_headers'] = {
          "Host" => "$$http_host",
          "X-Real-IP" => "$$remote_addr",
          "X-Forwarded-For" => "$$proxy_add_x_forwarded_for",
          "X-Forwarded-Proto" => "https",
          "X-Forwarded-Ssl" => "on"
        }
        nginx['real_ip_trusted_addresses'] = ${NGINX_REAL_IP_TRUSTED_ADDRESSES}
        nginx['real_ip_header'] = 'X-Real-IP'
        nginx['real_ip_recursive'] = 'on'

        registry_external_url 'https://${REGISTRY_HOSTNAME}'
        registry_nginx['listen_port'] = 80
        registry_nginx['listen_https'] = false
        registry_nginx['proxy_set_headers'] = {
          "Host" => "$$http_host",
          "X-Real-IP" => "$$remote_addr",
          "X-Forwarded-For" => "$$proxy_add_x_forwarded_for",
          "X-Forwarded-Proto" => "https",
          "X-Forwarded-Ssl" => "on"
        }
        registry_nginx['real_ip_trusted_addresses'] = ${NGINX_REAL_IP_TRUSTED_ADDRESSES}
        registry_nginx['real_ip_header'] = 'X-Real-IP'
        registry_nginx['real_ip_recursive'] = 'on'

        gitlab_rails['time_zone'] = '${TIME_ZONE}'

        gitlab_rails['smtp_enable'] = true
        gitlab_rails['smtp_address'] = "${NETWORK_HOST_IP}"
        gitlab_rails['smtp_port'] = 25
        gitlab_rails['smtp_enable_starttls_auto'] = false
        gitlab_rails['smtp_tls'] = false
        gitlab_rails['smtp_openssl_verify_mode'] = 'none'

        gitlab_rails['gitlab_email_from'] = '${EMAIL_FROM}'
        gitlab_rails['gitlab_email_display_name'] = '${EMAIL_DISPLAY_NAME}'
        gitlab_rails['gitlab_email_reply_to'] = '${EMAIL_REPLY_TO}'
        gitlab_rails['gitlab_email_subject_suffix'] = '${EMAIL_SUBJECT_SUFFIX}'

      VIRTUAL_HOST: "${GITLAB_HOSTNAME},${REGISTRY_HOSTNAME}"
      LETSENCRYPT_HOST: "${GITLAB_HOSTNAME},${REGISTRY_HOSTNAME}"
      LETSENCRYPT_EMAIL: "${LETSENCRYPT_EMAIL}"
    expose:
      - 80
    ports:
      - "0.0.0.0:${SSH_PORT}:22"
    volumes:
      - ./config:/etc/gitlab
      - ./logs:/var/log/gitlab
      - ./data:/var/opt/gitlab

networks:
  default:
    external:
      name: "${NETWORK}"
