version: "3"
services:
  bitwarden_rs:
    image: bitwardenrs/server:latest
    restart: always
    environment:
      VIRTUAL_HOST: "${BITWARDEN_RS_HOSTNAME}"
      LETSENCRYPT_HOST: "${BITWARDEN_RS_HOSTNAME}"
      LETSENCRYPT_EMAIL: "${LETSENCRYPT_EMAIL}"
      # WEBSOCKET_ENABLED: "true"
      SIGNUPS_ALLOWED: "${BW_SIGNUPS_ALLOWED}"
      INVITATIONS_ALLOWED: "${BW_INVITATIONS_ALLOWED}"
      LOG_FILE: "/data/bitwarden.log"
      SMTP_HOST: "${NETWORK_HOST_IP}"
      SMTP_PORT: "${BW_SMTP_PORT}"
      SMTP_USERNAME: "${BW_SMTP_USER}"
      SMTP_PASSWORD: "${BW_SMTP_PASS}"
      SMTP_SSL: "${BW_SMTP_SSL}"
      SMTP_FROM: "${BW_EMAIL_FROM}"
      SMTP_FROM_NAME: "${BW_EMAIL_FROM_NAME}"
      DOMAIN: "${BW_DOMAIN}"
      ADMIN_TOKEN: "${BW_ADMIN_TOKEN}"
      ROCKET_LIMITS: "${BW_ROCKET_LIMITS}"
      SHOW_PASSWORD_HINT: "${BW_SHOW_PASSWORD_HINT}"
      WEB_VAULT_ENABLED: "${BW_WEB_VAULT_ENABLED}"
    volumes:
      - ./data:/data
    expose:
      - 80

networks:
  default:
    external:
      name: ${NETWORK}
